CREATE TABLE CLIENTE(
  CLIENCODIGO BIGINT NOT NULL PRIMARY KEY,
  CLIENNOME TEXT NOT NULL,
  CLIENENDERECO VARCHAR(80) NOT NULL,
  CLIENDOC VARCHAR(12) NOT NULL
);

CREATE TABLE ARMAZEM(
  ARMCODIGO BIGINT NOT NULL PRIMARY KEY,
  ARMCAPACIDADE INTEGER NOT NULL,
  ARMENDERECO VARCHAR(80) NOT NULL,
  ARMDOC TEXT NOT NULL
);

CREATE TABLE EMPRESA(
  EMPCODIGO BIGINT NOT NULL PRIMARY KEY,
  EMPCNPJ VARCHAR(14) NOT NULL,
  EMPENDERECO VARCHAR(80) NOT NULL,
  EMPSITE VARCHAR(80) NOT NULL,
  EMPNICHO VARCHAR(80) NOT NULL
);

CREATE TABLE VEICULO(
  VEICODIGO BIGINT NOT NULL PRIMARY KEY,
  VEIDOC TEXT NOT NULL,
  VEICARGAMAX INTEGER NOT NULL,
  VEITIPO VARCHAR(30)
);

CREATE TABLE FUNCIONARIO(
  FUNCODIGO BIGINT NOT NULL PRIMARY KEY,
  FUNCNOME TEXT NOT NULL,
  FUNCTIPO VARCHAR(30) NOT NULL
);

CREATE TABLE PEDIDO(
    PEDCODIGO BIGINT NOT NULL PRIMARY KEY,
    PEDVALOR NUMERIC(10,2) NOT NULL,
    PEDORIGEM VARCHAR(80) NOT NULL,
    PEDDESTINO VARCHAR(80) NOT NULL,
    FUNCCODIGO BIGINT NOT NULL,
    ARMCODIGO BIGINT NOT NULL,
    EMPCODIGO BIGINT NOT NULL,
    CLIENCODIGO BIGINT NOT NULL,
    FOREIGN KEY(FUNCCODIGO) REFERENCES FUNCIONARIO,
    FOREIGN KEY(ARMCODIGO) REFERENCES ARMAZEM,
    FOREIGN KEY(EMPCODIGO) REFERENCES EMPRESA,
    FOREIGN KEY(CLIENCODIGO) REFERENCES CLIENTE    
);

CREATE TABLE RASTREAMENTO(
  RASTCODIGO BIGINT NOT NULL PRIMARY KEY,
  RASTISCADECARGA TEXT NOT NULL,
  RASTSTATUS CHAR(1),
  PEDCODIGO BIGINT NOT NULL,
  FOREIGN KEY(PEDCODIGO) REFERENCES PEDIDO
);

CREATE TABLE ROTA(
    ROTCODIGO BIGINT NOT NULL PRIMARY KEY,
    ROTCALCULOTEMPO INTEGER NOT NULL,
    ROTROTEIRO TEXT NOT NULL,
    ROTDESTINO VARCHAR(80)
);

CREATE TABLE ITINERARIA(
    PEDCODIGO BIGINT NOT NULL,
    ROTCODIGO BIGINT NOT NULL,
    FOREIGN KEY(PEDCODIGO) REFERENCES PEDIDO
    FOREIGN KEY(ROTCODIGO) REFERENCES ROTA
);

CREATE TABLE TRANSPORTA(
    TRANSPDATACHEGADA DATE NOT NULL,
    TRANSPDATASAIDA DATE NOT NULL,
    PEDCODIGO BIGINT NOT NULL,
    VEICODIGO BIGINT NOT NULL,
    FOREIGN KEY(PEDCODIGO) REFERENCES PEDIDO,
    FOREIGN KEY(VEICODIGO) REFERENCES VEICULO
);

